In [1]:
import open3d as o3d
from numba.core.errors import NumbaDeprecationWarning,NumbaPendingDeprecationWarning, NumbaWarning
import warnings
warnings.simplefilter('ignore', category=NumbaDeprecationWarning)
warnings.simplefilter('ignore', category=NumbaWarning)
import sys
sys.path.append('/kaggle/code/ConeDetectionPointpillars')

from second.data.CustomNuscDataset import * #to register dataset
from models import * #to register model
import torch
from second.utils.log_tool import SimpleModelLog
from second.builder import target_assigner_builder, voxel_builder
from second.protos import pipeline_pb2
from second.pytorch.builder import (box_coder_builder, input_reader_builder,
                                    lr_scheduler_builder, optimizer_builder,
                                    second_builder)
from second.pytorch.core import box_torch_ops
import torchplus
import re
import time
from pathlib import Path
import numpy as np
import pandas as pd
import json
from collections import defaultdict
from google.protobuf import text_format
# from lyft_dataset_sdk.utils.geometry_utils import *
from lyft_dataset_sdk.lyftdataset import Quaternion
from apex import amp
# from lyft_dataset_sdk.utils.data_classes import Box
from nuscenes.utils.geometry_utils import *
from nuscenes.utils.data_classes import Box
from second.utils.progress_bar import ProgressBar
from tqdm import tqdm, tqdm_notebook

#commented second.core.non_max_suppression, nms_cpu, __init__.py, 
# pytorch.core.box_torch_ops line 524

tensor([[-0.0772,  0.0050]])
tensor([[-0.7006,  1.5704]], device='cuda:0')
tensor([[-0.0772,  0.0050]])
False
tensor([[-0.0772,  0.0050]], device='cuda:0')
True
True


In [2]:
def _second_det_to_nusc_box(detection):
    from nuscenes.utils.data_classes import Box
    import pyquaternion
    box3d = detection["box3d_lidar"].detach().cpu().numpy()
    scores = detection["scores"].detach().cpu().numpy()
    labels = detection["label_preds"].detach().cpu().numpy()
    print(labels)
    box3d[:, 6] = -box3d[:, 6] - np.pi / 2
    box_list = []
    for i in range(box3d.shape[0]):
        quat = pyquaternion.Quaternion(axis=[0, 0, 1], radians=box3d[i, 6])
        velocity = (np.nan, np.nan, np.nan)
        if box3d.shape[1] == 9:
            velocity = (*box3d[i, 7:9], 0.0)
            # velo_val = np.linalg.norm(box3d[i, 7:9])
            # velo_ori = box3d[i, 6]
            # velocity = (velo_val * np.cos(velo_ori), velo_val * np.sin(velo_ori), 0.0)
        box = Box(
            box3d[i, :3],
            box3d[i, 3:6],
            quat,
            label=labels[i],
            score=scores[i],
            velocity=velocity)
        box_list.append(box)
    return box_list
def build_network(model_cfg, measure_time=False):
    voxel_generator = voxel_builder.build(model_cfg.voxel_generator)
    bv_range = voxel_generator.point_cloud_range[[0, 1, 3, 4]]
    box_coder = box_coder_builder.build(model_cfg.box_coder)
    target_assigner_cfg = model_cfg.target_assigner
    target_assigner = target_assigner_builder.build(target_assigner_cfg,
                                                    bv_range, box_coder)
    box_coder.custom_ndim = target_assigner._anchor_generators[0].custom_ndim
    net = second_builder.build(
        model_cfg, voxel_generator, target_assigner, measure_time=measure_time)
    return net


def merge_second_batch_multigpu(batch_list):
    if isinstance(batch_list[0], list):
        batch_list_c = []
        for example in batch_list:
            batch_list_c += example
        batch_list = batch_list_c

    example_merged = defaultdict(list)
    for example in batch_list:
        for k, v in example.items():
            example_merged[k].append(v)
    ret = {}
    for key, elems in example_merged.items():
        if key == 'metadata':
            ret[key] = elems
        elif key == "calib":
            ret[key] = {}
            for elem in elems:
                for k1, v1 in elem.items():
                    if k1 not in ret[key]:
                        ret[key][k1] = [v1]
                    else:
                        ret[key][k1].append(v1)
            for k1, v1 in ret[key].items():
                ret[key][k1] = np.stack(v1, axis=0)
        elif key == 'coordinates':
            coors = []
            for i, coor in enumerate(elems):
                coor_pad = np.pad(
                    coor, ((0, 0), (1, 0)), mode='constant', constant_values=i)
                coors.append(coor_pad)
            ret[key] = np.stack(coors, axis=0)
        elif key in ['gt_names', 'gt_classes', 'gt_boxes']:
            continue
        else:
            ret[key] = np.stack(elems, axis=0)

    return ret

def buildBBox(points,color = [1,0,0]):
    #print("Let's draw a cubic using o3d.geometry.LineSet")
    # points = [[0, 0, 0], [1, 0, 0], [0, 1, 0], [1, 1, 0], [0, 0, 1], [1, 0, 1],
    #           [0, 1, 1], [1, 1, 1]] x0y0z0, x0y0z1, x0y1z0, x0y1z1, x1y0z0, x1y0z1, x1y1z0, x1y1z1

    points = points[[0,4,3,7,1,5,2,6],:]
    lines = [[0, 1], [0, 2], [1, 3], [2, 3], [4, 5], [4, 6], [5, 7], [6, 7],
             [0, 4], [1, 5], [2, 6], [3, 7]]
    colors = [color for i in range(len(lines))]
    line_set = o3d.geometry.LineSet()
    line_set.points = o3d.utility.Vector3dVector(points)
    line_set.lines = o3d.utility.Vector2iVector(lines)
    line_set.colors = o3d.utility.Vector3dVector(colors)


    return  line_set
def merge_second_batch(batch_list):
    if isinstance(batch_list[0], list):
        batch_list_c = []
        for example in batch_list:
            batch_list_c += example
        batch_list = batch_list_c

    example_merged = defaultdict(list)
    for example in batch_list:
        for k, v in example.items():
            example_merged[k].append(v)
    ret = {}
    for key, elems in example_merged.items():
        if key in [
            'voxels', 'num_points', 'num_gt', 'voxel_labels', 'gt_names', 'gt_classes', 'gt_boxes'
        ]:
            ret[key] = np.concatenate(elems, axis=0)
        elif key == 'metadata':
            ret[key] = elems
        elif key == "calib":
            ret[key] = {}
            for elem in elems:
                for k1, v1 in elem.items():
                    if k1 not in ret[key]:
                        ret[key][k1] = [v1]
                    else:
                        ret[key][k1].append(v1)
            for k1, v1 in ret[key].items():
                ret[key][k1] = np.stack(v1, axis=0)
        elif key == 'coordinates':
            coors = []
            for i, coor in enumerate(elems):
                coor_pad = np.pad(
                    coor, ((0, 0), (1, 0)), mode='constant', constant_values=i)
                coors.append(coor_pad)
            ret[key] = np.concatenate(coors, axis=0)
        elif key == 'metrics':
            ret[key] = elems
        else:
            ret[key] = np.stack(elems, axis=0)
    return ret


def _worker_init_fn(worker_id):
    time_seed = np.array(time.time(), dtype=np.int32)
    np.random.seed(time_seed + worker_id)


def example_convert_to_torch(example, dtype=torch.float32,
                             device=None) -> dict:
    device = device or torch.device("cuda:0")
    example_torch = {}
    float_names = [
        "voxels", "anchors", "reg_targets", "reg_weights", "bev_map", "importance"
    ]
    for k, v in example.items():
        if k in ['gt_names', 'gt_classes', 'gt_boxes', 'points']:
            example_torch[k] = example[k]
            continue

        if k in float_names:
            # slow when directly provide fp32 data with dtype=torch.half
            example_torch[k] = torch.tensor(
                v, dtype=torch.float32, device=device).to(dtype)
        elif k in ["coordinates", "labels", "num_points"]:
            example_torch[k] = torch.tensor(
                v, dtype=torch.int32, device=device)
        elif k in ["anchors_mask"]:
            example_torch[k] = torch.tensor(
                v, dtype=torch.uint8, device=device)
        elif k == "calib":
            calib = {}
            for k1, v1 in v.items():
                calib[k1] = torch.tensor(
                    v1, dtype=dtype, device=device).to(dtype)
            example_torch[k] = calib
        elif k == "num_voxels":
            example_torch[k] = torch.tensor(v)
        else:
            example_torch[k] = v
    return example_torch


def time_to_str(t, mode='min'):
    if mode == 'min':
        t = int(t) / 60
        hr = t // 60
        min = t % 60
        return '%2d hr %02d m' % (hr, min)

    elif mode == 'sec':
        t = int(t)
        min = t // 60
        sec = t % 60
        return '%2d min %02d sec' % (min, sec)


    else:
        raise NotImplementedError


In [3]:
config_path = '/kaggle/code/ConeDetectionPointpillars/customNuscenes/configs/cones_pp_full_aug.config'
# config_path = '/kaggle/code/ConeDetectionPointpillars/customNuscenes/configs/cones_pp_initial_v2.config'
# config_path = '/kaggle/code/ConeDetectionPointpillars/customNuscenes/configs/cones_pp_initialak.config'
model_dir = f'/kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/cones_pp_full_aug/2021-2-13_11:1'
result_path = None
create_folder = False
display_step = 100
# pretrained_path="/kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/1611755918.3152874/29-1-2021_9:53/voxelnet-5850.tckpt"
pretrained_path = '/kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/cones_pp_full_aug/2021-2-13_11:1/voxelnet-35000.tckpt'
multi_gpu = False
measure_time = False
resume = True
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model_dir = str(Path(model_dir).resolve())
cur_time = time.localtime(time.time())
cur_time = f'{cur_time.tm_year}-{cur_time.tm_mon}-{cur_time.tm_mday}_{cur_time.tm_hour}:{cur_time.tm_min}'
if create_folder:
    if Path(model_dir).exists():
        model_dir = torchplus.train.create_folder(model_dir)
model_dir = Path(model_dir)

if not resume and model_dir.exists():
    raise ValueError("model dir exists and you don't specify resume")

model_dir.mkdir(parents=True, exist_ok=True)
if result_path is None:
    result_path = model_dir / 'results'/ cur_time
config_file_bkp = "pipeline.config"

if isinstance(config_path, str):
    config = pipeline_pb2.TrainEvalPipelineConfig()
    with open(config_path, "r") as f:
        proto_str = f.read()
        text_format.Merge(proto_str, config)
else:
    config = config_path
    proto_str = text_format.MessageToString(config, indent=2)

with (model_dir / config_file_bkp).open('w') as f:
    f.write(proto_str)
# Read config file
input_cfg = config.train_input_reader
eval_input_cfg = config.eval_input_reader
model_cfg = config.model.second  # model's config
train_cfg = config.train_config  # training config


In [4]:
# Build neural network
net = build_network(model_cfg, measure_time).to(device)

target_assigner = net.target_assigner
voxel_generator = net.voxel_generator
print("num parameter: ", len(list(net.parameters())))
torchplus.train.try_restore_latest_checkpoints(model_dir, [net])

num parameter:  64
Restoring parameters from /kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/cones_pp_full_aug/2021-2-13_11:1/voxelnet-35000.tckpt


In [5]:
if pretrained_path is not None:
    print('warning pretrain is loaded after restore, careful with resume')
    model_dict = net.state_dict()
    pretrained_dict = torch.load(pretrained_path)

    new_pretrained_dict = {}
    for k, v in pretrained_dict.items():
        if k in model_dict and v.shape == model_dict[k].shape:
            new_pretrained_dict[k] = v
    print("Load pretrained parameters: ")
    for k, v in new_pretrained_dict.items():
        print(k, v.shape)
    model_dict.update(new_pretrained_dict)
    net.load_state_dict(model_dict)
    net.clear_global_step()
    net.clear_metrics()
if multi_gpu:
    net_parallel = torch.nn.DataParallel(net)
else:
    net_parallel = net
optimizer_cfg = train_cfg.optimizer
loss_scale = train_cfg.loss_scale_factor
fastai_optimizer = optimizer_builder.build(
    optimizer_cfg,
    net,
    mixed=False,
    loss_scale=loss_scale)
if loss_scale < 0:
    loss_scale = "dynamic"
if train_cfg.enable_mixed_precision:
    max_num_voxels = input_cfg.preprocess.max_number_of_voxels * input_cfg.batch_size
    print("max_num_voxels: %d" % (max_num_voxels))

    net, amp_optimizer = amp.initialize(net, fastai_optimizer,
                                        opt_level="O1",
                                        keep_batchnorm_fp32=None,
                                        loss_scale=loss_scale)
    net.metrics_to_float()
else:
    amp_optimizer = fastai_optimizer
torchplus.train.try_restore_latest_checkpoints(model_dir, [fastai_optimizer])
lr_scheduler = lr_scheduler_builder.build(optimizer_cfg, amp_optimizer, train_cfg.steps)

if train_cfg.enable_mixed_precision:
    float_dtype = torch.float16
else:
    float_dtype = torch.float32

if multi_gpu:
    num_gpu = torch.cuda.device_count()
    print(f"MULTI_GPU: use {num_gpu} gpus")
    collate_fn = merge_second_batch_multigpu
else:
    collate_fn = merge_second_batch
    num_gpu = 1

warning pretrain is loaded after restore, careful with resume
Load pretrained parameters: 
global_step torch.Size([1])
voxel_feature_extractor.pfn_layers.0.linear.weight torch.Size([64, 10])
voxel_feature_extractor.pfn_layers.0.norm.weight torch.Size([64])
voxel_feature_extractor.pfn_layers.0.norm.bias torch.Size([64])
voxel_feature_extractor.pfn_layers.0.norm.running_mean torch.Size([64])
voxel_feature_extractor.pfn_layers.0.norm.running_var torch.Size([64])
voxel_feature_extractor.pfn_layers.0.norm.num_batches_tracked torch.Size([])
rpn.blocks.0.1.weight torch.Size([64, 64, 3, 3])
rpn.blocks.0.2.weight torch.Size([64])
rpn.blocks.0.2.bias torch.Size([64])
rpn.blocks.0.2.running_mean torch.Size([64])
rpn.blocks.0.2.running_var torch.Size([64])
rpn.blocks.0.2.num_batches_tracked torch.Size([])
rpn.blocks.0.4.weight torch.Size([64, 64, 3, 3])
rpn.blocks.0.5.weight torch.Size([64])
rpn.blocks.0.5.bias torch.Size([64])
rpn.blocks.0.5.running_mean torch.Size([64])
rpn.blocks.0.5.running_va

In [6]:
dataset = input_reader_builder.build(
    input_cfg,
    model_cfg,
    training=True,
    voxel_generator=voxel_generator,
    target_assigner=target_assigner,
    multi_gpu=multi_gpu
)
dataloader = torch.utils.data.DataLoader(
    dataset,
    batch_size=input_cfg.batch_size * num_gpu,
    shuffle=True,
    num_workers=input_cfg.preprocess.num_workers * num_gpu,
    pin_memory=False,
    collate_fn=collate_fn,
    worker_init_fn=_worker_init_fn,
    drop_last=not multi_gpu
)


feature_map_size [1, 100, 150]
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 29.666 seconds.
Reverse indexing ...
Done reverse indexing in 5.2 seconds.


In [7]:
dataset[1]

INFO - 2021-02-23 12:06:32,960 - transforms - finding looplift candidates


[[ 0.81603203  0.81709019  0.81762322 ...  0.60296096  0.61220096
   0.61976863]
 [ 2.91564093  3.05792392  3.21156221 ... 10.0054728  10.03215923
  10.02510468]
 [ 0.1343773   0.14571364  0.15668149 ...  3.2926691   3.53506267
   3.77595573]
 [15.         15.         15.         ... 46.         36.
  32.        ]]
[[ 0.81603203  2.91564093  0.1343773  -0.44117647  0.        ]
 [ 0.81709019  3.05792392  0.14571364 -0.44117647  0.        ]
 [ 0.81762322  3.21156221  0.15668149 -0.44117647  0.        ]
 ...
 [ 0.60296096 10.0054728   3.2926691  -0.31960784  0.19962096]
 [ 0.61220096 10.03215923  3.53506267 -0.35882353  0.19962096]
 [ 0.61976863 10.02510468  3.77595573 -0.3745098   0.19962096]]


{'voxels': array([[[ 0.40021371,  3.08460096,  0.15569393, -0.44117647,
           0.        ],
         [ 0.41717715,  3.07956217,  0.15921866, -0.44117647,
           0.        ],
         [ 0.43371414,  3.07775214,  0.16078528, -0.44117647,
           0.        ],
         ...,
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ]],
 
        [[ 0.38742086,  3.22193075,  0.16668269, -0.44117647,
           0.        ],
         [ 0.30033613,  3.20813662,  0.17115533, -0.44509804,
           0.        ],
         [ 0.31610236,  3.2174703 ,  0.16700034, -0.44117647,
           0.        ],
         ...,
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ],
         [ 0.

In [26]:
d = dataset[1]
for k in d.keys():
    if isinstance(d[k], dict):
        print(k, "dict")
        continue
    print(k, d[k].shape)
print(d)


[[ 0.81603203  0.81709019  0.81762322 ...  0.60296096  0.61220096
   0.61976863]
 [ 2.91564093  3.05792392  3.21156221 ... 10.0054728  10.03215923
  10.02510468]
 [ 0.1343773   0.14571364  0.15668149 ...  3.2926691   3.53506267
   3.77595573]
 [15.         15.         15.         ... 46.         36.
  32.        ]]
[[ 0.81603203  2.91564093  0.1343773  -0.44117647  0.        ]
 [ 0.81709019  3.05792392  0.14571364 -0.44117647  0.        ]
 [ 0.81762322  3.21156221  0.15668149 -0.44117647  0.        ]
 ...
 [ 0.60296096 10.0054728   3.2926691  -0.31960784  0.19962096]
 [ 0.61220096 10.03215923  3.53506267 -0.35882353  0.19962096]
 [ 0.61976863 10.02510468  3.77595573 -0.3745098   0.19962096]]
voxels (22394, 100, 5)
num_points (22394,)
coordinates (22394, 3)
num_voxels (1,)
metrics dict
anchors (30000, 7)
gt_names (8,)
labels (30000,)
reg_targets (30000, 7)
importance (30000,)
metadata dict
{'voxels': array([[[-1.2293828 , -2.52684823,  0.31437412, -0.44117647,
          0.        ],
   

In [16]:
dataset[1].keys()

[[ 0.81603203  0.81709019  0.81762322 ...  0.60296096  0.61220096
   0.61976863]
 [ 2.91564093  3.05792392  3.21156221 ... 10.0054728  10.03215923
  10.02510468]
 [ 0.1343773   0.14571364  0.15668149 ...  3.2926691   3.53506267
   3.77595573]
 [15.         15.         15.         ... 46.         36.
  32.        ]]
[[ 0.81603203  2.91564093  0.1343773  -0.44117647  0.        ]
 [ 0.81709019  3.05792392  0.14571364 -0.44117647  0.        ]
 [ 0.81762322  3.21156221  0.15668149 -0.44117647  0.        ]
 ...
 [ 0.60296096 10.0054728   3.2926691  -0.31960784  0.19962096]
 [ 0.61220096 10.03215923  3.53506267 -0.35882353  0.19962096]
 [ 0.61976863 10.02510468  3.77595573 -0.3745098   0.19962096]]


dict_keys(['voxels', 'num_points', 'coordinates', 'num_voxels', 'metrics', 'anchors', 'gt_names', 'labels', 'reg_targets', 'importance', 'metadata'])

In [49]:
a = torch.as_tensor(dataset[0]["coordinates"][:,0])
a.unsqueeze(0)

[[ 0.80464275  0.80564527  0.80599708 ...  0.59282028  0.60208186
   0.60958528]
 [ 2.91067808  3.04589131  3.19936666 ... 10.02903209 10.0436566
  10.02856053]
 [ 0.13911276  0.15427481  0.16503456 ...  3.30142298  3.54246499
   3.78220166]
 [16.         14.         13.         ... 48.         34.
  32.        ]]
[[ 0.80464275  2.91067808  0.13911276 -0.4372549   0.        ]
 [ 0.80564527  3.04589131  0.15427481 -0.44509804  0.        ]
 [ 0.80599708  3.19936666  0.16503456 -0.44901961  0.        ]
 ...
 [ 0.59282028 10.02903209  3.30142298 -0.31176471  0.19829798]
 [ 0.60208186 10.0436566   3.54246499 -0.36666667  0.19829798]
 [ 0.60958528 10.02856053  3.78220166 -0.3745098   0.19829798]]


tensor([[0, 0, 0,  ..., 0, 0, 0]], dtype=torch.int32)

In [43]:
a.unsqueeze()

AttributeError: 'numpy.ndarray' object has no attribute 'unsqueeze'

In [ ]:
print(net)

In [ ]:
# # [line for line in dataset[0]['reg_targets'] for i in line if i != 0]
# res = []
# for line in dataset[1]['reg_targets']:
#     for i in line:
#         if i != 0:
#             print(line)
#             res.append(line)
#             break
# #     break
# res

In [ ]:
len([i for i in dataset[1]['labels'] if i == 0])

In [9]:
eval_dataset = input_reader_builder.build(
    eval_input_cfg,
    model_cfg,
    training=False,
    voxel_generator=voxel_generator,
    target_assigner=target_assigner)
eval_dataloader = torch.utils.data.DataLoader(
    eval_dataset,
    batch_size=input_cfg.batch_size,
    shuffle=True,
    num_workers=eval_input_cfg.preprocess.num_workers,
    pin_memory=False,
    collate_fn=merge_second_batch)

feature_map_size [1, 100, 150]
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.942 seconds.
Reverse indexing ...
Done reverse indexing in 0.1 seconds.


In [10]:
len(eval_dataset)

47

In [27]:
eval_dataset[0]

{'voxels': array([[[ 2.87861935e-01, -6.90282527e+00, -2.68713817e-02,
          -4.45098039e-01,  4.97839451e-02],
         [ 2.08736939e-01, -6.90953233e+00, -2.69478965e-02,
          -4.45098039e-01,  4.97839451e-02],
         [ 2.63588540e-01, -6.97065800e+00, -2.70102925e-02,
          -4.41176471e-01,  0.00000000e+00],
         ...,
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00]],
 
        [[ 2.78481420e+00,  4.89472728e+00,  4.97334215e-03,
          -4.37254902e-01,  1.99628115e-01],
         [ 2.75554073e+00,  4.86044707e+00,  1.85989135e-02,
          -3.66666667e-01,  0.00000000e+00],
         [ 2.78066329e+00,  4.84081703e+00,  2.04177941e-02,
          -3.70588235e-01,  0.00000000e+00],
         ...,
     

In [30]:
torch.ones([1, 100])

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:

model_dir = model_dir / cur_time
model_dir.mkdir(parents=True, exist_ok=True)

In [ ]:
model_dir

In [ ]:

model_logging = SimpleModelLog(model_dir)
model_logging.open()
model_logging.log_text(proto_str + "\n", 0, tag="config")

start_step = net.get_global_step()
total_step = train_cfg.steps
t = time.time()
steps_per_eval = train_cfg.steps_per_eval
clear_metrics_every_epoch = train_cfg.clear_metrics_every_epoch

amp_optimizer.zero_grad()
step_times = []
step = start_step
run = True
ave_valid_loss = 0.0


In [ ]:
# Ver2
print(total_step)
try:
    start_tic = time.time()
    print("num samples: %d" % (len(dataset)))
    while run == True:
        if clear_metrics_every_epoch:
            net.clear_metrics()
        for example in tqdm_notebook(dataloader):
            lr_scheduler.step(net.get_global_step())
            example.pop("metrics")
            example_torch = example_convert_to_torch(example, float_dtype)

            ret_dict = net_parallel(example_torch)
            loss = ret_dict["loss"].mean()
            cls_loss_reduced = ret_dict["cls_loss_reduced"].mean()
            loc_loss_reduced = ret_dict["loc_loss_reduced"].mean()

            if train_cfg.enable_mixed_precision:
                if net.get_global_step() < 100:
                    loss *= 1e-3
                with amp.scale_loss(loss, amp_optimizer) as scaled_loss:
                    scaled_loss.backward()
            else:
                loss.backward()
            torch.nn.utils.clip_grad_norm_(net.parameters(), 10.0)
            amp_optimizer.step()
            amp_optimizer.zero_grad()
            net.update_global_step()

            cls_preds = ret_dict["cls_preds"]
            labels = example_torch["labels"]
            cared = ret_dict["cared"]

            net_metrics = net.update_metrics(cls_loss_reduced,
                                             loc_loss_reduced, cls_preds,
                                             labels, cared)
            step_time = (time.time() - t)
            step_times.append(step_time)
            t = time.time()
            metrics = {}
            global_step = net.get_global_step()

            if global_step % display_step == 0:
                net.eval()
                det = net(example_torch)
                net.train()
                eta = time.time() - start_tic
                if measure_time:
                    for name, val in net.get_avg_time_dict().items():
                        print(f"avg {name} time = {val * 1000:.3f} ms")

                metrics["step"] = global_step
                metrics['epoch'] = global_step / len(dataloader)
                metrics['steptime'] = np.mean(step_times)
                metrics['valid'] = ave_valid_loss
                step_times = []

                metrics["loss"] = net_metrics['loss']['cls_loss'] + net_metrics['loss']['loc_loss']
                metrics["cls_loss"] = net_metrics['loss']['cls_loss']
                metrics["loc_loss"] = net_metrics['loss']['loc_loss']

                if model_cfg.use_direction_classifier:
                    dir_loss_reduced = ret_dict["dir_loss_reduced"].mean()
                    metrics["dir_rt"] = float(
                        dir_loss_reduced.detach().cpu().numpy())

                metrics['lr'] = float(amp_optimizer.lr)
                metrics['eta'] = time_to_str(eta)
                model_logging.log_metrics(metrics, global_step)

                net.clear_metrics()
            if global_step % steps_per_eval == 0:
                torchplus.train.save_models(model_dir, [net, amp_optimizer],
                                            net.get_global_step())
                model_logging.log_text(f"Model saved: {model_dir}, {net.get_global_step()}", global_step)
                net.eval()
                result_path_step = result_path / f"step_{net.get_global_step()}"
                result_path_step.mkdir(parents=True, exist_ok=True)
                model_logging.log_text("########################", global_step)
                model_logging.log_text(" EVALUATE", global_step)
                model_logging.log_text("########################", global_step)
                model_logging.log_text("Generating eval predictions...", global_step)
                t = time.time()
                detections = []
                prog_bar = ProgressBar()
                net.clear_timer()
                cnt = 0
                for example in tqdm_notebook(iter(eval_dataloader)):
                    example = example_convert_to_torch(example, float_dtype)
                    detections += net(example)
                sec_per_ex = len(eval_dataset) / (time.time() - t)
                model_logging.log_text(
                    f'generate eval predictions finished({sec_per_ex:.2f}/s). Start eval:',
                    global_step)
                result_dict = eval_dataset.dataset.evaluation(
                    detections, str(result_path_step)
                )
                for k, v in result_dict['results'].items():
                    model_logging.log_text(f"Evaluation {k}", global_step)
                    model_logging.log_text(v, global_step)
                model_logging.log_metrics(result_dict["detail"], global_step)
                with open(result_path_step/"result.pkl", "wb") as f:
                    pickle.dump(detections,f)
                net.train()

            step += 1
            if step >= total_step:
                break
        if step >= total_step:
            break
except Exception as e:
    model_logging.log_text(str(e), step)
    model_logging.log_text(json.dumps(example['metadata'], indent=2), step)
    torchplus.train.save_models(model_dir, [net, amp_optimizer], step)
    raise e
finally:
    model_logging.close()
torchplus.train.save_models(model_dir, [net, amp_optimizer], step)
# python /kaggle/code/ConeDetectionPointpillars/second/data/nusc_eval.py --root_path="/media/starlet/LdTho/data/sets/nuscenes/v1.0-trainval" --version="v1.0-trainval" --eval_version=detection_cvpr_2019 --res_path="/kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/1611755918.3152874/results/step_20/result_nusc.json" --eval_set=val --output_dir="/kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/1611755918.3152874/results/step_20"

In [ ]:
net.train()

## Visualizing

In [ ]:
NameMappingInverse = {
    "barrier": "movable_object.barrier",
    "bicycle": "vehicle.bicycle",
    "bus": "vehicle.bus.rigid",
    "car": "vehicle.car",
    "construction_vehicle": "vehicle.construction",
    "motorcycle": "vehicle.motorcycle",
    "pedestrian": "human.pedestrian.adult",
    "traffic_cone": "movable_object.trafficcone",
    "trailer": "vehicle.trailer",
    "truck": "vehicle.truck",
}
def visualize_evaluation(config_path, model_dir, pretrained_path, multi_gpu=False):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    if isinstance(config_path, str):
        config = pipeline_pb2.TrainEvalPipelineConfig()
        with open(config_path, "r") as f:
            proto_str = f.read()
            text_format.Merge(proto_str, config)
    else:
        config = config_path
        proto_str = text_format.MessageToString(config, indent=2)


    # Read config file
    input_cfg = config.train_input_reader
    eval_input_cfg = config.eval_input_reader
    model_cfg = config.model.second  # model's config
    train_cfg = config.train_config

    # Build neural network
    net = build_network(model_cfg).to(device)

    # Build Model
    target_assigner = net.target_assigner
    voxel_generator = net.voxel_generator
    print("num parameter: ", len(list(net.parameters())))
    torchplus.train.try_restore_latest_checkpoints(model_dir, [net])

    if pretrained_path is not None:
        print('warning pretrain is loaded after restore, careful with resume')
        model_dict = net.state_dict()
        pretrained_dict = torch.load(pretrained_path)

        new_pretrained_dict = {}
        for k, v in pretrained_dict.items():
            if k in model_dict and v.shape == model_dict[k].shape:
                new_pretrained_dict[k] = v
        print("Load pretrained parameters: ")
        for k, v in new_pretrained_dict.items():
            print(k, v.shape)
        model_dict.update(new_pretrained_dict)
        net.load_state_dict(model_dict)
        net.clear_global_step()
        net.clear_metrics()
    if multi_gpu:
        net_parallel = torch.nn.DataParallel(net)
    else:
        net_parallel = net

    optimizer_cfg = train_cfg.optimizer
    loss_scale = train_cfg.loss_scale_factor
    fastai_optimizer = optimizer_builder.build(
        optimizer_cfg,
        net,
        mixed=False,
        loss_scale=loss_scale)
    if loss_scale < 0:
        loss_scale = "dynamic"
    if train_cfg.enable_mixed_precision:
        max_num_voxels = input_cfg.preprocess.max_number_of_voxels * input_cfg.batch_size
        print("max_num_voxels: %d" % (max_num_voxels))

        net, amp_optimizer = amp.initialize(net, fastai_optimizer,
                                            opt_level="O1",
                                            keep_batchnorm_fp32=None,
                                            loss_scale=loss_scale)
        net.metrics_to_float()
    else:
        amp_optimizer = fastai_optimizer
    torchplus.train.try_restore_latest_checkpoints(model_dir, [fastai_optimizer])
    lr_scheduler = lr_scheduler_builder.build(optimizer_cfg, amp_optimizer, train_cfg.steps)
    if train_cfg.enable_mixed_precision:
        float_dtype = torch.float16
    else:
        float_dtype = torch.float32

    if multi_gpu:
        num_gpu = torch.cuda.device_count()
        print(f"MULTI_GPU: use {num_gpu} gpus")
        collate_fn = merge_second_batch_multigpu
    else:
        collate_fn = merge_second_batch
        num_gpu = 1

    eval_dataset = input_reader_builder.build(
        eval_input_cfg,
        model_cfg,
        training=False,
        voxel_generator=voxel_generator,
        target_assigner=target_assigner)
    eval_dataloader = torch.utils.data.DataLoader(
        eval_dataset,
        batch_size=input_cfg.batch_size,
        shuffle=True,
        num_workers=eval_input_cfg.preprocess.num_workers,
        pin_memory=False,
        collate_fn=merge_second_batch)

    # Start visualizing
    net.eval()
    # example = next(iter(dataloader))
    for example in iter(eval_dataloader):
        detection = example_convert_to_torch(example, float_dtype)
        detection = net(detection)
        print(detection)
        filtered_sample_tokens = eval_dataset.dataset.filtered_sample_tokens
        # filtered_sample_tokens = dataset.dataset.filtered_sample_tokens
        index = filtered_sample_tokens.index(detection[0]['metadata']['token'])

        gt_example = eval_dataset.dataset.get_sensor_data(index)
        # gt_example = dataset.dataset.get_sensor_data(index)
        points = gt_example['lidar']['points']
        pc_range = model_cfg.voxel_generator.point_cloud_range
        points = np.array(
            [p for p in points if (pc_range[0] < p[0] < pc_range[3]) & (pc_range[1] < p[1] < pc_range[4]) & (
                    pc_range[2] < p[2] < pc_range[5])])

        gt_boxes = gt_example['lidar']['annotations']['boxes']
        gt_labels = gt_example['lidar']['annotations']['names']
        c = points[:, 3].reshape(-1, 1)
        c = np.concatenate([c, c, c], axis=1)
        points = points[:, 0:3]
        pc = o3d.geometry.PointCloud()
        pc.points = o3d.utility.Vector3dVector(points)
        pc.colors = o3d.utility.Vector3dVector(c)
        mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=2.0,
                                                                       origin=[-0, -0, -0])
        geo = [pc, mesh_frame]
        geo = add_prediction_per_class(eval_dataset.dataset.nusc,
                                       detection, gt_boxes, gt_labels,
                                       target_assigner.classes, geo)
        o3d.visualization.draw_geometries(geo)

    net.train()


In [ ]:
def add_prediction_per_class(nusc, detection, gt_boxes, gt_labels, class_names, geometries):
    color = {
    "traffic_cone": (1,0,0),
    "gt_traffic_cone": (0,1,0),
    "pedestrian": (1,1,0),
    "gt_pedestrian": (0,0,1)
    }
    det_boxes = detection[0]['box3d_lidar'].cpu().detach().numpy()
    det_labels = detection[0]['label_preds'].cpu().detach().numpy()
    det_scores = detection[0]['scores'].cpu().detach().numpy()
    for i, class_name in enumerate(class_names):
        mask = np.logical_and(det_labels == i, det_scores > 0.5)
        class_det_boxes = det_boxes[mask]
        class_det_scores = det_scores[mask]
        class_det_labels = det_labels[mask]
        print(len(class_det_boxes),len(class_det_scores),len(class_det_labels))
        print(class_det_scores)
        class_gt_boxes = gt_boxes[gt_labels == class_name]
        class_gt_labels = gt_labels[gt_labels == class_name]

        rbbox_corners = box_np_ops.center_to_corner_box3d(class_det_boxes[:, :3],
                                                          class_det_boxes[:, 3:6],
                                                          class_det_boxes[:, 6],
                                                          origin=(0.5, 0.5, 0.5), axis=2)
        gt_rbbox_corners = box_np_ops.center_to_corner_box3d(class_gt_boxes[:, :3],
                                                             class_gt_boxes[:, 3:6],
                                                             class_gt_boxes[:, 6],
                                                             origin=(0.5, 0.5, 0.5), axis=2)
        for j in range(len(rbbox_corners)):
            geometries.append(buildBBox(rbbox_corners[j],
                                        color=color[class_name]))
        for j in range(len(gt_rbbox_corners)):
            geometries.append(buildBBox(gt_rbbox_corners[j], 
                                        color=color[f'gt_{class_name}']))
    return geometries

In [ ]:
visualize_evaluation('/kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/cones_pp_full_aug/pipeline.config',
                     '/kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/cones_pp_full_aug/2021-2-13_11:1', 
                     '/kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/cones_pp_full_aug/2021-2-13_11:1/voxelnet-35000.tckpt',
                     )

## Test with baraja

In [ ]:

pc_file_name = "/media/starlet/LdTho/data/sets/1612769433360603.pcd"
pcd = o3d.io.read_point_cloud(pc_file_name)
points = np.asarray(pcd.points)

In [ ]:
from second.data.preprocess import merge_second_batch, prep_pointcloud
NameMappingInverse = {
    "barrier": "movable_object.barrier",
    "bicycle": "vehicle.bicycle",
    "bus": "vehicle.bus.rigid",
    "car": "vehicle.car",
    "construction_vehicle": "vehicle.construction",
    "motorcycle": "vehicle.motorcycle",
    "pedestrian": "human.pedestrian.adult",
    "traffic_cone": "movable_object.trafficcone",
    "trailer": "vehicle.trailer",
    "truck": "vehicle.truck",
}
#set input
config_path = '/kaggle/code/ConeDetectionPointpillars/customNuscenes/configs/cones_pp_full_aug.config'
model_dir = '/kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/cones_pp_full_aug/2021-2-13_11:1'
pretrained_path = '/kaggle/code/ConeDetectionPointpillars/customNuscenes/outputs/cones_pp_full_aug/2021-2-13_11:1/voxelnet-35000.tckpt'
multi_gpu = False
# build network and other stuff
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
if isinstance(config_path, str):
    config = pipeline_pb2.TrainEvalPipelineConfig()
    with open(config_path, "r") as f:
        proto_str = f.read()
        text_format.Merge(proto_str, config)
else:
    config = config_path
    proto_str = text_format.MessageToString(config, indent=2)


# Read config file
input_cfg = config.train_input_reader
eval_input_cfg = config.eval_input_reader
model_cfg = config.model.second  # model's config
train_cfg = config.train_config

# Build neural network
net = build_network(model_cfg).to(device)

# Build Model
target_assigner = net.target_assigner
voxel_generator = net.voxel_generator
print("num parameter: ", len(list(net.parameters())))
torchplus.train.try_restore_latest_checkpoints(model_dir, [net])

if pretrained_path is not None:
    print('warning pretrain is loaded after restore, careful with resume')
    model_dict = net.state_dict()
    pretrained_dict = torch.load(pretrained_path)

    new_pretrained_dict = {}
    for k, v in pretrained_dict.items():
        if k in model_dict and v.shape == model_dict[k].shape:
            new_pretrained_dict[k] = v
    print("Load pretrained parameters: ")
    for k, v in new_pretrained_dict.items():
        print(k, v.shape)
    model_dict.update(new_pretrained_dict)
    net.load_state_dict(model_dict)
    net.clear_global_step()
    net.clear_metrics()
if multi_gpu:
    net_parallel = torch.nn.DataParallel(net)
else:
    net_parallel = net

optimizer_cfg = train_cfg.optimizer
loss_scale = train_cfg.loss_scale_factor
fastai_optimizer = optimizer_builder.build(
    optimizer_cfg,
    net,
    mixed=False,
    loss_scale=loss_scale)
if loss_scale < 0:
    loss_scale = "dynamic"
if train_cfg.enable_mixed_precision:
    max_num_voxels = input_cfg.preprocess.max_number_of_voxels * input_cfg.batch_size
    print("max_num_voxels: %d" % (max_num_voxels))

    net, amp_optimizer = amp.initialize(net, fastai_optimizer,
                                        opt_level="O1",
                                        keep_batchnorm_fp32=None,
                                        loss_scale=loss_scale)
    net.metrics_to_float()
else:
    amp_optimizer = fastai_optimizer
torchplus.train.try_restore_latest_checkpoints(model_dir, [fastai_optimizer])
lr_scheduler = lr_scheduler_builder.build(optimizer_cfg, amp_optimizer, train_cfg.steps)
if train_cfg.enable_mixed_precision:
    float_dtype = torch.float16
else:
    float_dtype = torch.float32

if multi_gpu:
    num_gpu = torch.cuda.device_count()
    print(f"MULTI_GPU: use {num_gpu} gpus")
    collate_fn = merge_second_batch_multigpu
else:
    collate_fn = merge_second_batch
    num_gpu = 1

# Start visualizing
net.eval()



In [73]:
from second.data.preprocess import merge_second_batch, prep_pointcloud

pc_file_name = "/media/starlet/LdTho/data/sets/1614053547.551486.pcd"
pcd = o3d.io.read_point_cloud(pc_file_name)
points = np.asarray(pcd.points)
pc_range = model_cfg.voxel_generator.point_cloud_range
points = np.array([p for p in points if (pc_range[0] < p[0] < pc_range[3])
                   & (pc_range[1] < p[1] < pc_range[4])
                   & (0.05 < p[2] < pc_range[5])])

points = np.concatenate([points.transpose(), 
                         np.array([np.repeat(0.0, points.shape[0])]),
                         np.array([np.repeat(0.0, points.shape[0])])],axis = 0).transpose()
points = points[~np.isnan(points).any(axis=1)]

input_dict = {
    'lidar': {
        'type': 'lidar',
        'points': points
    },
    'metadata': {
        'token': pc_file_name
    }
}

out_size_factor = model_cfg.rpn.layer_strides[0] // model_cfg.rpn.upsample_strides[0]
example = prep_pointcloud(input_dict=input_dict,
                          root_path= None ,
                          voxel_generator= voxel_generator,
                          target_assigner= target_assigner,
                          max_voxels= 70000,
                          training= False,
                          create_targets=False,
                          shuffle_points=input_cfg.preprocess.shuffle_points,
                          num_point_features=model_cfg.num_point_features,
                          remove_outside_points=False,
                          anchor_cache=None,
                          anchor_area_threshold=input_cfg.preprocess.anchor_area_threshold,
                          out_size_factor=out_size_factor,
                          out_dtype=np.float32
                          )
# example["points"] = points
example["metadata"] = input_dict["metadata"]
example = [example]
print(example)

[{'voxels': array([[[  2.7952251 ,   2.6065896 ,   0.11079672,   0.        ,
           0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           0.        ],
        ...,
        [  0.        ,   0.        ,   0.        ,   0.        ,
           0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           0.        ]],

       [[  2.8023841 ,   2.6132655 ,   0.12595397,   0.        ,
           0.        ],
        [  2.8119824 ,   2.622216  ,   0.14039153,   0.        ,
           0.        ],
        [  2.8132339 ,   2.6032598 ,   0.19666678,   0.        ,
           0.        ],
        ...,
        [  0.        ,   0.        ,   0.        ,   0.        ,
           0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ,
     

In [74]:
eval_dataloader = torch.utils.data.DataLoader(
        example,
        batch_size=input_cfg.batch_size,
        shuffle=True,
        num_workers=eval_input_cfg.preprocess.num_workers,
        pin_memory=False,
        collate_fn=merge_second_batch)

In [75]:
net.eval()
example = next(iter(eval_dataloader))
detection = example_convert_to_torch(example, float_dtype)
detection = net(detection)

In [80]:
points = np.asarray(pcd.points)
points = np.array(
    [p for p in points if (pc_range[0] < p[0] < pc_range[3]) & (pc_range[1] < p[1] < pc_range[4]) & (
           pc_range[2]  < p[2] < pc_range[5])])
points = np.concatenate([points.transpose(), 
                         np.array([np.repeat(0.0, points.shape[0])]),
                         np.array([np.repeat(0.0, points.shape[0])])],axis = 0).transpose()
points = points[~np.isnan(points).any(axis=1)]

c = points[:, 3].reshape(-1, 1)
c = np.concatenate([c, c, c], axis=1)
points = points[:, 0:3]

pc = o3d.geometry.PointCloud()
pc.points = o3d.utility.Vector3dVector(points)
pc.colors = o3d.utility.Vector3dVector(c)
mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=2.0,
                                                               origin=[-0, -0, -0])
geo = [pc, mesh_frame]


In [81]:
det_boxes = detection[0]['box3d_lidar'].cpu().detach().numpy()
det_labels = detection[0]['label_preds'].cpu().detach().numpy()
det_scores = detection[0]['scores'].cpu().detach().numpy()

In [82]:
class_names = ['traffic_cone']
color = {
"traffic_cone": (1,0,0),
"gt_traffic_cone": (0,1,0),
"pedestrian": (1,1,0),
"gt_pedestrian": (0,0,1)
}
for i, class_name in enumerate(class_names):
    mask = np.logical_and(det_labels == i, det_scores > 0.5)
    class_det_boxes = det_boxes[mask]
    class_det_scores = det_scores[mask]
    class_det_labels = det_labels[mask]
    print(len(class_det_boxes),len(class_det_scores),len(class_det_labels))
    print(class_det_scores)
    rbbox_corners = box_np_ops.center_to_corner_box3d(class_det_boxes[:, :3],
                                                      class_det_boxes[:, 3:6],
                                                      class_det_boxes[:, 6],
                                                      origin=(0.5, 0.5, 0.5), axis=2)

    for j in range(len(rbbox_corners)):
        geo.append(buildBBox(rbbox_corners[j],
                                    color=color[class_name]))


16 16 16
[0.77662295 0.75201255 0.7318258  0.72671664 0.65797806 0.65323746
 0.6278371  0.6213686  0.6204492  0.61687815 0.59496313 0.5778527
 0.56613845 0.55953074 0.5567611  0.5071559 ]


In [83]:
o3d.visualization.draw_geometries(geo)


In [ ]:
points

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(points[:,2],bins = 20)

In [ ]:
example['voxels'].shape

In [ ]:
plt.hist(example['num_points'])

In [ ]:
plt.hist(dataset[1]['num_points'])

In [57]:
detection

[{'box3d_lidar': tensor([[  5.4123,   2.1952,   0.1914,   0.3746,   0.3783,   0.8061,   1.2520],
          [  2.5964,  -1.4935,   0.2891,   0.3673,   0.3712,   0.7470,   1.5391],
          [  5.4012,  -1.3905,   0.1797,   0.3688,   0.3736,   0.8234,   1.1309],
          [  2.8603,   2.5337,   0.2676,   0.3751,   0.3761,   0.7556,   1.5693],
          [ 11.8338,   1.9946,   0.1895,   0.3701,   0.3731,   0.8448,   1.6123],
          [ 15.3248,  -1.9501,   0.2637,   0.3800,   0.3767,   0.8296,   2.3359],
          [  8.6497,  -1.3051,   0.2207,   0.3733,   0.3732,   0.7785,   1.9570],
          [ 18.4739,  -2.1518,   0.2539,   0.3659,   0.3594,   0.8519,   0.9390],
          [ 21.8709,   1.2486,   0.2500,   0.3820,   0.3793,   0.9415,   1.5713],
          [  8.7848,   1.9966,   0.1699,   0.3512,   0.3523,   0.7662,   2.5352],
          [ 15.2564,   1.6977,   0.2324,   0.3930,   0.3970,   0.8521,   1.7754],
          [ 26.0562,  -2.8520,   0.2891,   0.4887,   0.4920,   1.0001,   1.5518],
 