In [1]:
import torch
import torch.nn as nn
dev = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
t1 = torch.randn(1,2)
t2 = torch.randn(1,2).to(dev)
print(t1)  # tensor([[-0.2678,  1.9252]])
print(t2)  # tensor([[ 0.5117, -3.6247]], device='cuda:0')
t1.to(dev)
print(t1)  # tensor([[-0.2678,  1.9252]])
print(t1.is_cuda) # False
t1 = t1.to(dev)
print(t1)  # tensor([[-0.2678,  1.9252]], device='cuda:0')
print(t1.is_cuda) # True

class M(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(1,2)

    def forward(self, x):
        x = self.l1(x)
        return x
model = M()   # not on cuda
model.to(dev) # is on cuda (all parameters)
print(next(model.parameters()).is_cuda) # True

tensor([[-0.0680,  1.4359]])
tensor([[-1.1951, -0.3269]], device='cuda:0')
tensor([[-0.0680,  1.4359]])
False
tensor([[-0.0680,  1.4359]], device='cuda:0')
True
True


In [2]:
import open3d as o3d
from numba.core.errors import NumbaDeprecationWarning,NumbaPendingDeprecationWarning, NumbaWarning
import warnings
warnings.simplefilter('ignore', category=NumbaDeprecationWarning)
warnings.simplefilter('ignore', category=NumbaWarning)
import sys
sys.path.append('/kaggle/code/lyft-tho')

# from CustomNuscDataset import * #to register dataset
from models import * #to register model
import torch
from second.utils.log_tool import SimpleModelLog
from second.builder import target_assigner_builder, voxel_builder
from second.protos import pipeline_pb2
from second.pytorch.builder import (box_coder_builder, input_reader_builder,
                                    lr_scheduler_builder, optimizer_builder,
                                    second_builder)
from second.pytorch.core import box_torch_ops
import torchplus
import re
import time
from pathlib import Path
import numpy as np
import pandas as pd
import json
from collections import defaultdict
from google.protobuf import text_format
# from lyft_dataset_sdk.utils.geometry_utils import *
from lyft_dataset_sdk.lyftdataset import Quaternion
# from lyft_dataset_sdk.utils.data_classes import Box
from nuscenes.utils.geometry_utils import *
from nuscenes.utils.data_classes import Box

INFO - 2021-01-17 17:06:15,821 - driver - init


tensor([[-1.9056,  0.3707]])
tensor([[ 0.8771, -0.1843]], device='cuda:0')
tensor([[-1.9056,  0.3707]])
False
tensor([[-1.9056,  0.3707]], device='cuda:0')
True
True


NvvmError: Failed to compile

libnvvm : error: -arch=compute_80 is an unsupported option
NVVM_ERROR_INVALID_OPTION

In [6]:
from pathlib import Path

In [9]:
device = torch.device('cuda')

In [10]:
import torch

In [ ]:
import torch
import torch.nn as nn
dev = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
t1 = torch.randn(1,2)
t2 = torch.randn(1,2).to(dev)
print(t1)  # tensor([[-0.2678,  1.9252]])
print(t2)  # tensor([[ 0.5117, -3.6247]], device='cuda:0')
t1.to(dev) 
print(t1)  # tensor([[-0.2678,  1.9252]]) 
print(t1.is_cuda) # False
t1 = t1.to(dev)
print(t1)  # tensor([[-0.2678,  1.9252]], device='cuda:0') 
print(t1.is_cuda) # True

class M(nn.Module):
    def __init__(self):        
        super().__init__()        
        self.l1 = nn.Linear(1,2)

    def forward(self, x):                      
        x = self.l1(x)
        return x
model = M()   # not on cuda
model.to(dev) # is on cuda (all parameters)
print(next(model.parameters()).is_cuda) # True

/home/starlet/anaconda3/envs/spconv12/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning: 
GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the GeForce RTX 3080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))


In [4]:
!pwd

/kaggle/code/lyft-tho/customNuscenes


In [5]:
config_path = './configs/cones_pp_initial.config'
from google.protobuf import text_format
import sys
sys.path.append('/kaggle/code/lyft-tho')
from second.protos import pipeline_pb2

config = pipeline_pb2.TrainEvalPipelineConfig()
with open(config_path, "r") as f:
    proto_str = text_format.Merge(f.read(), config)

In [6]:
print(proto_str)

model {
  second {
    network_class_name: "VoxelNet"
    voxel_generator {
      voxel_size: 0.10000000149011612
      voxel_size: 0.10000000149011612
      voxel_size: 8.0
      point_cloud_range: -100.0
      point_cloud_range: -100.0
      point_cloud_range: -5.0
      point_cloud_range: 100.0
      point_cloud_range: 100.0
      point_cloud_range: 3.0
      max_number_of_points_per_voxel: 15
    }
    voxel_feature_extractor {
      module_class_name: "PillarFeatureNet"
      num_filters: 64
      num_input_features: 4
    }
    middle_feature_extractor {
      module_class_name: "PointPillarsScatter"
      num_input_features: 64
      downsample_factor: 1
    }
    rpn {
      module_class_name: "RPNV2"
      layer_nums: 3
      layer_nums: 5
      layer_nums: 5
      layer_strides: 2
      layer_strides: 2
      layer_strides: 2
      num_filters: 64
      num_filters: 128
      num_filters: 256
      upsample_strides: 0.25
      upsample_strides: 0.5
      upsample_strides: 1.0

In [20]:
config_path = './configs/cones_pp_initial.config'
model_dir = './outputs'
create_folder = False
measure_time = False
resume = False

In [21]:
## def run_train
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model_dir = str(Path(model_dir).resolve())
if create_folder:
    if Path(model_dir).exists():
        model_dir = torchplus.train.create_folder(model_dir)
model_dir = Path(model_dir)

if not resume and model_dir.exists():
    raise ValueError("model dir exists and you don't specify resume")

model_dir.mkdir(parents=True, exist_ok= True)
config_file_bkp = "pipeline.config"

if isinstance(config_path, str):
    config = pipeline_pb2.TrainEvalPipelineConfig()
    with open(config_path, "r") as f:
        proto_str = f.read()
        text_format.Merge(proto_str, config)
else:
    config = config_path
    proto_str = text_format.MessageToString(config, indent=2)

with (model_dir/config_file_bkp).open('w') as f:
    f.write(proto_str)
# Read config file
input_cfg = config.train_input_reader
eval_input_cfg = config.eval_input_reader
model_cfg = config.model.second # model's config
train_cfg = config.train_config # training config


In [22]:
def build_network(model_cfg, measure_time=False):
    voxel_generator = voxel_builder.build(model_cfg.voxel_generator)
    bv_range = voxel_generator.point_cloud_range[[0, 1, 3, 4]]
    box_coder = box_coder_builder.build(model_cfg.box_coder)
    target_assigner_cfg = model_cfg.target_assigner
    target_assigner = target_assigner_builder.build(target_assigner_cfg,
                                                    bv_range, box_coder)
    box_coder.custom_ndim = target_assigner._anchor_generators[0].custom_ndim
    net = second_builder.build(
        model_cfg, voxel_generator, target_assigner, measure_time=measure_time)
    return net

In [24]:
model_dir.exists()

True

In [25]:
net = build_network(model_cfg, measure_time)

In [26]:
net

VoxelNet(
  (voxel_feature_extractor): PillarFeatureNet(
    (pfn_layers): ModuleList(
      (0): PFNLayer(
        (linear): DefaultArgLayer(in_features=9, out_features=64, bias=False)
        (norm): DefaultArgLayer(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      )
    )
  )
  (middle_feature_extractor): PointPillarsScatter()
  (rpn): RPNV2(
    (blocks): ModuleList(
      (0): Sequential(
        (0): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
        (1): DefaultArgLayer(64, 64, kernel_size=(3, 3), stride=(2, 2), bias=False)
        (2): DefaultArgLayer(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (3): ReLU()
        (4): DefaultArgLayer(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (5): DefaultArgLayer(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (6): ReLU()
        (7): DefaultArgLayer(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  

In [35]:
len(list(net.parameters()))

64

In [4]:
import torch
torch.cuda.is_available()

True

In [5]:
!conda install -c open3d-admin open3d

Solving environment: done

## Package Plan ##

  environment location: /home/starlet/anaconda3/envs/spconv12cuda11

  added / updated specs:
    - open3d


The following NEW packages will be INSTALLED:

  ipywidgets         pkgs/main/noarch::ipywidgets-7.6.3-pyhd3eb1b0_1
  jupyterlab_widgets pkgs/main/noarch::jupyterlab_widgets-1.0.0-pyhd3eb1b0_1
  open3d             open3d-admin/linux-64::open3d-0.11.2-py38_0
  widgetsnbextension pkgs/main/linux-64::widgetsnbextension-3.5.1-py38_0


Proceed ([y]/n)? ^C

CondaSystemExit: 
Operation aborted.  Exiting.

